name = "Cabricality"
author = "Yjn024, KrLite"
version = "0.1.0-dev14-zh_cn"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06ca75306099e427d417a175b9820d9e11b55e3b907886abae98e00fb995a7d2"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
