name = "Cabricality"
author = "Yjn024, KrLite"
version = "0.1.0-dev15-zh_cn"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b4a794f4ab45e893d6225d0d2006cc30fd4087e07f1cf252a822fb85770edde"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
