name = "Cabricality"
author = "Yjn024, KrLite"
version = "0.1.0-dev13-zh_cn"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af40a4bd4e731e3ce79555b0010a2a89685d0ba62e437855f452cb643b19aaee"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
