name = "Cabricality"
author = "Yjn024, KrLite"
version = "0.1.0-dev12-zh_cn"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da390bddb803531d20196b8addf1c03021e8d76bcf852178a78cb5466c0cc3de"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
